export enum Role {
  VISITOR = 'VISITOR',
  PARTICIPANT = 'PARTICIPANT',
  JUDGE = 'JUDGE',
  ORGANIZER = 'ORGANIZER',
  ADMIN = 'ADMIN',
}

export enum EventStatus {
  DRAFT = 'DRAFT',
  REGISTRATION_OPEN = 'REGISTRATION_OPEN',
  SUBMISSION_OPEN = 'SUBMISSION_OPEN',
  SUBMISSION_FROZEN = 'SUBMISSION_FROZEN',
  JUDGING_OPEN = 'JUDGING_OPEN',
  RESULTS_FINALIZED = 'RESULTS_FINALIZED',
  RESULTS_PUBLISHED = 'RESULTS_PUBLISHED',
  ARCHIVED = 'ARCHIVED',
}

export enum ProjectEligibility {
  PENDING = 'PENDING',
  ELIGIBLE = 'ELIGIBLE',
  DISQUALIFIED = 'DISQUALIFIED',
}

export enum BallotStatus {
  UNASSIGNED = 'UNASSIGNED',
  ASSIGNED = 'ASSIGNED',
  IN_PROGRESS = 'IN_PROGRESS',
  SUBMITTED = 'SUBMITTED',
  LOCKED = 'LOCKED',
  REOPENED = 'REOPENED',
  VOIDED = 'VOIDED',
}

export enum AutopilotMode {
  OFF = 'OFF',
  ASSIST = 'ASSIST',
  FULL = 'FULL',
}
